
- hosts: all
  tasks:
    - name: Install base software
      become: yes
      become_method: su
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:  
        packages:
        - htop
        - rsync
        - tmux
        - vim-nox
        - sudo

    - name: Update all packages to the latest version
      become: yes
      become_method: su
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes

